config/routes.rb
Rails.application.routes.draw do
  namespace :apis do
    resources :favorites, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :blogs do
    post "/comment" => "comments#create", as: "comment"
    delete "/comment/:comment_id" => "comments#destroy", as: "comments"
    collection do
      get "/favorites" => "blogs#favorites", as: "favorites"
    end
  end
  post "/topic" => "topics#create", as: "topic"
  delete "/topic/:id" => "topics#destroy", as: "topics"
  resources :experiences
  root 'page#top'

  namespace :admin do
    root "home#top"
    get "users" => "home#users"
    get "user_logs/:id/" => "home#user_logs", as: 'user_logs'
    patch "/:id/user_accept" => "home#user_accept", as: 'user_accept'
    get "blogs" => "home#blogs"
    patch "/:id/blog_publish" => "home#blog_publish", as: 'blog_publish'
  end
  # LetterOpener
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  acts_as_taggable

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fav_users, through: :favorites, source: :user

  scope :not_pined, -> { where.not(is_pin: true) }

  SCOPES = {
    '全体' => 0,
    '登録済' => 1,
  }

  def fav(user)
    favorites.create(user_id: user.id)
  end

  def un_fav(user)
    favorites.find_by(user_id: user.id).destroy
  end

  def fav?(user)
    fav_users.include?(user)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, only: [:favorites]
  before_action :user_confirmed?, except: [:index, :show]
  before_action :is_admin?, except: [:index, :show]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :reject_not_admin, only: [:show]
  before_action :unpined, only: [:create, :update]

  # GET /blogs
  # GET /blogs.json
  def index
    @pined_blog = Blog.find_by(is_pin: true)
    @blogs = Blog.not_pined.order(created_at: :desc).page(params[:page]).per(PER)
    @topics = Topic.all.order(created_at: :desc)
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if current_user.nil? && @blog.public_scope == 1
      redirect_to blogs_path, alert: '登録済みのユーザのみ閲覧可能です 登録かログインをしてください'
    end

    @blog.update(viewer: @blog.viewer+=1) if !current_user.try(:admin?)
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    if params[:preview] || !@blog.save
      render :new
    else
      redirect_to @blog, notice: '記事の作成に成功しました'
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    @blog.attributes = blog_params

    if params[:preview] || !@blog.update(blog_params)
      render :edit
    else
      redirect_to @blog, notice: 'ブログの更新に成功しました'
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: 'ブログを削除しました'
  end

  def favorites
    @favorites = Blog.where(id: current_user.favorites.pluck(:blog_id)).page(params[:page]).per(PER)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
  end

  def unpined
    Blog.update_all(is_pin: false) unless blog_params[:is_pin] == '0' || @blog.is_pin?
  end

  def reject_not_admin
    if !current_user.try(:admin?) && !@blog.published_on
      redirect_to blogs_path, alert: 'この記事は管理者以外のユーザーには閲覧が制限されています'
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def blog_params
    params.require(:blog).permit(:title, :content, :public_scope, :public, :published_on, :tag_list, :is_pin)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="col-10" style="padding: 0px;">
  <%= link_to blog, class: 'not-underline' do %>
    <article class="media">
      <div class="media-image-area">
        <%= image_tag 'all/small-no-image.png', class: 'media-image-thumb' %>
      </div>
      <div class="media-body">
        <div class="media-info">
          <% if blog.is_publish %>
            <% case blog.public_scope %>
            <% when 0 %>
              <span class="badge badge-success">全体に公開中</span>
            <% when 1 %>
              <span class="text-white badge badge-warning">登録済ユーザ限定</span>
            <% end %>
            <%= blog.published_on.strftime('%Y年%m月%d日') %>に投稿
          <% else %>
            <span class="badge badge-danger">非公開</span>
          <% end %>
        </div>
        <div class="media-title d-block d-md-none">
          <%= blog.title.truncate(12) %>
        </div>
        <div class="media-title d-none d-md-block">
          <%= blog.title %>
        </div>
          <div class="media-tags">
            <ul class="tag-list clearfix d-none d-md-block">
              <% blog.tag_list.each do |tag| %>
                <li class="tag-list-item"><%= tag %></li>
              <% end %>
            </ul>
            <ul class="tag-list clearfix d-block d-md-none">
              <li class="tag-list-item"><%= blog.tag_list.first %></li>
              <% if blog.tag_list.size > 1 %>
                <li class="tag-list-item"><%= "+#{blog.tag_list.size - 1}" %></li>
              <% end %>
            </ul>
          </div>
      </div>
    </article>
  <% end %>
</div>
  <div class="col-2 favorite-btn-area">
    <% if user_signed_in? %>
      <div id="blog-<%= blog.id %>" data-blog-id="<%= blog.id %>">
        <%= render "apis/favorites/favorite", blog: blog %>
      </div>
    <% else %>
      <i class="far fa-star favorite-btn" style="cursor: pointer;" onclick="promptLogin()"></i>
    <% end %>
  </div>

app/views/blogs/_comment_area.html.erb
<div class="row mb-5">
  <div class="col-md-12">
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <% if current_user.nil? %>
          <h1 class="display-4">ログイン状態でないとコメントができません</h1>
          <p class="lead">残念なことにログインしないとコメントはできません。</p>
        <% else %>
          <h1 class="display-4">コメント欄</h1>
        <% end %>
        <ul class="comment-warning">
          <li>コメントには会員登録・ログインが必要ですが、コメントするときに登録時に入力した内容が表示されることはありません</li>
          <li>誤った内容でコメントしてしまった場合もユーザ側で削除することが可能です</li>
          <li>管理人の心はものすごく折れやすいので、誹謗中傷コメントはご遠慮ください</li>
          <li>ご意見やご指摘いただけるとすごく幸せを感じることができるのでぜひみなさまこぞってコメントくださいまし</li>
        </ul>
        <% if current_user.nil? %>
          <%= link_to 'ログイン', new_user_session_path, class: 'btn btn-dark btn-lg' %>
          <%= link_to '新規登録', new_user_registration_path, class: 'btn btn-secondary btn-lg' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% if current_user.present? %>
  <div class="row mb-5">
    <div class="col-md-12">
      <%= form_with model: Comment.new, url: blog_comment_path(blog), local: true do |form| %>
        <div class="form-group">
          <%= form.label 'お名前 (必須)' %>
          <%= form.text_field :author, class: 'form-control comment-form-control' %>
        </div>
        <div class="form-group">
          <%= form.label 'コメント (必須)' %>
          <%= form.text_area :content, class: 'form-control comment-form-control' %>
        </div>
        <%= form.submit 'コメントする', class: 'btn btn-dark btn-lg' %>
      <% end %>
    </div>
  </div>
<% end %>
<% blog.comments.each do |comment| %>
  <div class="row">
    <div class="col-md-12">
      <div class="comment-wrapper">
        <div class="clearfix">
          <span class="float-left comment-author"><%= comment.author %></span>
          <% if comment.user.try(:id) == current_user.try(:id) || current_user.try(:admin?) %><span class="float-left pl-5"><%= link_to '削除', blog_comments_path(blog, comment.id), class: 'btn btn-danger', method: :delete %></span><% end %>
          <span class="float-right commented-at"><%= comment.created_at.strftime("%y年%m月%d日 %H:%M") %></span>
        </div>
        <div class="arrow_box">
          <%= comment.content %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/blogs/_form.html.erb
<style>
  img
  {
    width: 100%;
    margin: 30px 0;
  }

  .area-break h1
  {
    margin: 30px 0;
    padding-left: 10px;
    padding-bottom: 10px;
    border-bottom: 1px solid #ccc;
  }

  h2
  {
    margin: 30px 0 10px;
  }

  a
  {
    color: #000;
    text-decoration: underline;
    transition: .2s;
  }

  a:hover
  {
    color: #ccc;
    text-decoration: none;
  }

  ul, ol
  {
    padding-left: 15px;
  }

  form textarea
  {
    font-family: "Ricty Diminished Discord";
    src: local("Ricty Diminished Discord");
    font-size: 1.6rem !important;
  }


  form select
  {
    font-size: 1rem;
  }
</style>
<div class="row">
  <div class="col-md-12">
    <%= form_with(model: blog, local: true) do |form| %>

      <div class="form-group">
        <%= form.label "記事タイトル" %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-check">
        <%= form.check_box :is_pin, class: 'form-check-input', checked: blog.is_pin? %>
        <%= form.label :is_pin, "ピン留", class: 'form-check-label ml-3' %>
      </div>

      <div class="form-group">
        <%= form.label :public_scope, "公開範囲" %>
        <%= form.select :public_scope, Blog::SCOPES.to_a, {}, class: 'custom-select' %>
      </div>

      <div class="form-group">
        <%= form.label "タグ" %>
        <%= form.text_field :tag_list, value: blog.tag_list.join(','), data: { role: "tagsinput" }, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label "内容" %>
        <%= form.text_area :content, class: 'form-control', style: "height: 500px;" %>
      </div>

      <div class="actions">
        <%= form.submit btn_txt, class: 'btn btn-dark' %>
        <%= submit_tag 'プレビュー', name: 'preview', class: 'btn btn-warning' %>
        <%= link_to 'Show', blog_path(blog), class: 'btn btn-secondary' if action_name == 'edit' %>
        <%= link_to 'Back', blogs_path, class: 'btn btn-light' %>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <h1 class="profile-heading"><span><%= blog.title %></span></h1>
    <% if !blog.content.nil? %>
      <div class="area-break">
        <%= markdown(blog.content).html_safe %>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
  <h1>Editing Blog</h1>
  <%= render 'form', blog: @blog, btn_txt: '更新' %>
</div>

app/views/blogs/favorites.html.erb
<div class="container" style="margin-top: 100px;">
  <div class="row">
    <div class="col-md-4 bai-jamjuree">
      <h1 class="blog-name"><i class="fab fa-blogger"></i> Hirrot's Blog <span class="text-white badge badge-warning">FAVORITES</span></h1>
      <% if current_user.try(:admin?) %>
        <%= link_to 'New Blog', new_blog_path, class: 'btn btn-dark btn-lg' %>
      <% end %>
    </div>

    <div class="col-md-8">
      <% if @favorites.empty? %>
        <div class="jumbotron">
          <h1>まだお気に入りはありません。</h1>
          <p class="lead">記事をお気に入りすることで気になった記事のみ表示することができます。</p>
          <hr class="my-4">
          <p>ブログ一覧ページに行って早速記事をお気に入りしましょう。</p>
          <%= link_to 'ブログ一覧', blogs_path, class: 'btn btn-dark btn-lg' %>
        </div>
      <% else %>
        <%= paginate @favorites %>
        <% @favorites.each do |blog| %>
          <div class="row">
            <%= render 'blog', blog: blog %>
          </div>
        <% end %>
        <%= paginate @favorites %>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="container" style="margin-top: 100px;">
  <div class="row">
    <div class="col-md-4 bai-jamjuree">
      <h1 class="blog-name"><i class="fab fa-blogger"></i> Hirrot's Blog</h1>
      <% if current_user.try(:admin?) %>
        <%= link_to 'New Blog', new_blog_path, class: 'btn btn-dark btn-lg' %>
      <% end %>
      <div class="news-area my-4">
        <div class="news-heading clearfix">
          <h2 class="float-left">NEWS</h2>
          <span class="float-right">
            <i id="toggle-news" class="fas fa-toggle-off fa-2x"></i>
          </span>
        </div>
        <ul id="news-wrapper" class="news-wrapper area-break">
          <% @topics.each do |topic| %>
            <li>
              <div class="text-right pr-3">
                <% if current_user.try(:admin?) %>
                  <%= link_to '削除する', topics_path(topic), class: 'badge badge-danger', method: :delete, data: { confirm: '本当に削除しますか？' } %>
                <% end %>
                <%= topic.created_at.strftime("%y年%m月%d日 %H:%M") %>
              </div>
              <div class="news-content">
                <% if (topic.created_at.to_date) >= (Date.today - 1) %>
                  <span class="text-white badge badge-warning">new!</span>
                <% end %>
                <%= topic.title %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>

      <% if current_user.try(:admin?) %>
        <%= form_with model: Topic.new, url: topic_path do |form| %>
          <div class="form-group">
            <%= form.label '新着情報を追加' %>
            <%= form.text_field :title, class: 'form-control' %>
          </div>
          <%= form.submit '追加する', class: 'btn btn-dark' %>
        <% end %>
      <% end %>
    </div>

    <div class="col-md-8">
      <% if @pined_blog.present? %>
        <p><i class="fas fa-map-pin"></i> ピン留めされた投稿</p>
        <div class="row pined mb-5">
          <%= render 'blog', blog: @pined_blog %>
        </div>
      <% end %>
      <%= paginate @blogs %>
      <% @blogs.each do |blog| %>
        <div class="row">
          <%= render 'blog', blog: blog %>
        </div>
      <% end %>
      <%= paginate @blogs %>
    </div>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog, btn_txt: '新規登録' %>
</div>

app/views/blogs/show.html.erb
<style>
  img
  {
    width: 100%;
    margin: 30px 0;
  }

  .area-break h1
  {
    margin: 30px 0;
    padding-left: 10px;
    padding-bottom: 10px;
    border-bottom: 1px solid #ccc;
  }

  h2
  {
    margin: 30px 0 10px;
  }

  p a
  {
    color: #000;
    text-decoration: underline;
    transition: .2s;
  }

  p a:hover
  {
    color: #ccc;
    text-decoration: none;
  }

  ul, ol
  {
    padding-left: 15px;
  }

  .comment-warning
  {
    font-size: 1.2rem;
  }
</style>
<div class="blog-wrapper container" style="margin-top: 100px;">
  <h1 class="profile-heading"><span><%= @blog.title %></span></h1>
  <div class="row">
    <div class="blogs-back-content col-md-9 mx-auto area-break">
      <div class="blogs-back-area">
        <%= link_to blogs_path, class: 'text-center blogs-back-btn' do %>
          <i class="fas fa-arrow-left"></i>
        <% end %>
      </div>
      <div class="text-right">
        <span class="mr-3"><i class="fas fa-eye"></i> <%= @blog.viewer.to_s(:delimited) %> views</span>
        <% if @blog.is_publish? %>
          <span class="badge badge-success">公開中</span>
        <% else %>
          <span class="badge badge-warning">未公開</span>
        <% end %>
        <%= @blog.published_on.try(:strftime, '%y年%m月%d日') %>
      </div>
      <% @blog.tag_list.each do |tag| %>
        <span class="badge badge-dark"><%= tag %></span>
      <% end %>
      <div id="social-share-button-wrapper">
        <%= social_share_button_tag(@blog.title) %>
      </div>
      <div class="area-break mb-5">
        <%= markdown(@blog.content).html_safe %>
      </div>
      <%= render 'comment_area', blog: @blog %>
      <%= link_to '一覧へ戻る', blogs_path, class: 'btn btn-secondary' %>
      <% if current_user.try(:admin?) %>
        <%= link_to '編集する', edit_blog_path(@blog), class: 'btn btn-dark' %>
        <%= link_to '削除する', blog_path(@blog), class: 'btn btn-danger', method: :delete, data: { confirm: '一度行った処理は戻せません。本当に削除しますか？' } %>
      <% end %>
    </div>
  </div>
</div>