config/routes.rb
Rails.application.routes.draw do
  namespace :apis do
    resources :favorites, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :blogs do
    post "/comment" => "comments#create", as: "comment"
    delete "/comment/:comment_id" => "comments#destroy", as: "comments"
    collection do
      get "/favorites" => "blogs#favorites", as: "favorites"
    end
  end
  post "/topic" => "topics#create", as: "topic"
  delete "/topic/:id" => "topics#destroy", as: "topics"
  resources :experiences
  root 'page#top'

  namespace :admin do
    root "home#top"
    get "users" => "home#users"
    get "user_logs/:id/" => "home#user_logs", as: 'user_logs'
    patch "/:id/user_accept" => "home#user_accept", as: 'user_accept'
    get "blogs" => "home#blogs"
    patch "/:id/blog_publish" => "home#blog_publish", as: 'blog_publish'
  end
  # LetterOpener
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/experience.rb
class Experience < ApplicationRecord
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :user_confirmed?
  before_action :is_admin?, except: [:index, :show]
  before_action :set_experience, only: [:show, :edit, :update, :destroy]

  # GET /experiences
  # GET /experiences.json
  def index
    @experiences = Experience.all.order(beginning_at: :asc)
  end

  # GET /experiences/1
  # GET /experiences/1.json
  def show
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences
  # POST /experiences.json
  def create
    @experience = Experience.new(experience_params)

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: '経歴を追加しました' }
        format.json { render :show, status: :created, location: @experience }
      else
        format.html { render :new }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiences/1
  # PATCH/PUT /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to @experience, notice: '経歴を更新しました' }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1
  # DELETE /experiences/1.json
  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url, notice: 'Experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experience_params
      params.require(:experience).permit(:title, :description, :beginning_at, :quit_at, :reference_url)
    end
end

app/views/experiences/_form.html.erb
<div class="row">
  <div class="col-md-5 mx-auto">
    <%= form_with(model: experience, url: url, local: true) do |form| %>
      <div class="form-group">
        <%= form.label '学校名/会社名' %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label '概要' %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label '開始年月' %>
        <%= form.date_field :beginning_at, class: 'form-control' %>
      </div>

      <div class="checkbox">
        <label>
          <%= check_box_tag :quit_at_check_box %>
          在籍中の場合
        </label>
      </div>

      <div id="quit_at_wrap" class="form-group">
        <%= form.label '終了年月' %>
        <%= form.date_field :quit_at, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label 'URL' %>
        <%= form.text_field :reference_url, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit btn_txt, class: 'btn btn-dark' %>
        <%= link_to '詳細画面に戻る', experience_path(experience), class:'btn btn-secondary' if action_name == 'edit' %>
        <%= link_to '一覧画面に戻る', experiences_path, class:'btn btn-light' %>
      </div>
    <% end %>
  </div>
</div>

app/views/experiences/edit.html.erb
<div class="container">
  <h1 class="profile-heading mb-5"><span><%= @experience.title %>の編集</span></h1>
  <%= render 'form', experience: @experience, url: experience_path, btn_txt: '更新' %>
</div>

app/views/experiences/index.html.erb
<div class="experience-top-img mb-5 bai-jamjuree">
  <div class="top-title">
    <h1>Hiroto Shibutani</h1>
    <p>You know who I am.</p>
    <%= link_to blogs_path, class: 'btn btn-dark btn-lg' do %>
      What one likes, one will do well
    <% end %>
  </div>
</div>

<div class="container">
  <h1 class="profile-heading"><span>Career</span></h1>
</div>

<% if current_user.admin? %>
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <%= link_to '経歴を追加', new_experience_path, class: 'btn btn-success' %>
      </div>
    </div>
  </div>
<% end %>

<section class="cd-timeline js-cd-timeline">
  <div class="cd-timeline__container">
    <% @experiences.each do |experience| %>
      <div class="cd-timeline__block js-cd-block">
        <div class="cd-timeline__img cd-timeline__img--picture js-cd-img">
        </div>

        <div class="cd-timeline__content js-cd-content">
          <h2><%= experience.title %></h2>
          <p><%= experience.description.html_safe %></p>
          <%= link_to '詳細', experience_path(experience), class: 'btn btn-light' %>
          <%= link_to '参考URL', experience.reference_url, class: 'btn btn-secondary' %>
          <% if current_user.admin? %>
            <%= link_to '削除', experience_path(experience), method: :delete, class: 'btn btn-danger' %>
          <% end %>
          <span class="cd-timeline__date">
            <%= experience.beginning_at.try(:strftime, '%Y年%m月') %> 〜 <%= experience.quit_at.nil? ? '在職中' : experience.quit_at.strftime('%Y年%m月') %>
          </span>
        </div>
      </div>
    <% end %>

    <div class="cd-timeline__block js-cd-block">
      <div class="cd-timeline__img cd-timeline__img--movie js-cd-img">
      </div>

      <div class="cd-timeline__content js-cd-content">
        <h2>そして人生は続いていく</h2>
        <p>
          知識に対するのどの渇きを潤せ<br />
          Quench your thirst for knowledge...
        </p>
        <span class="cd-timeline__date"><%= Date.today.strftime('%Y年%m月') %></span>
      </div>
    </div>
  </div>
</section>

app/views/experiences/new.html.erb
<div class="container">
  <h1 class="profile-heading mb-5"><span>経歴を新規追加</span></h1>
  <%= render 'form', experience: @experience, url: experiences_path, btn_txt: '新規作成' %>
</div>

app/views/experiences/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 mx-auto">
      <h1 class="profile-heading"><span><%= @experience.title %></span></h1>
      <h2>概要</h2>
      <p><%= @experience.description %></p>
      <p><%= @experience.beginning_at.try(:strftime, '%Y年%m月') %>〜<%= @experience.quit_at.nil? ? '在職中' : @experience.quit_at.strftime('%Y年%m月') %></p>
      <h2>URL</h2>
      <p><%= link_to @experience.reference_url, @experience.reference_url %></p>
      <%= link_to '一覧に戻る', experiences_path, class: 'btn btn-light' %>
      <% if current_user.admin? %>
        <%= link_to '編集する', edit_experience_path(@experience), class: 'btn btn-dark' %>
      <% end %>
    </div>
  </div>
</div>