config/routes.rb
Rails.application.routes.draw do
  namespace :apis do
    resources :favorites, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :blogs do
    post "/comment" => "comments#create", as: "comment"
    delete "/comment/:comment_id" => "comments#destroy", as: "comments"
    collection do
      get "/favorites" => "blogs#favorites", as: "favorites"
    end
  end
  post "/topic" => "topics#create", as: "topic"
  delete "/topic/:id" => "topics#destroy", as: "topics"
  resources :experiences
  root 'page#top'

  namespace :admin do
    root "home#top"
    get "users" => "home#users"
    get "user_logs/:id/" => "home#user_logs", as: 'user_logs'
    patch "/:id/user_accept" => "home#user_accept", as: 'user_accept'
    get "blogs" => "home#blogs"
    patch "/:id/blog_publish" => "home#blog_publish", as: 'blog_publish'
  end
  # LetterOpener
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::ApplicationController
  def top
  end

  def users
    @users = User.all
    @users = @users.includes(:role).where(roles: { is_confirm: false }) if params[:type] == 'is_not_confirm'
    @users = @users.includes(:role).where(roles: { is_confirm: true }) if params[:type] == 'is_confirm'
    @users = @users.order(created_at: :desc)
  end

  def user_logs
    user = User.find(params[:id])
    @logs = user.track_viewers.order(landing_at: :desc)
  end

  def user_accept
    user = User.find(params[:id])
    role = user.role
    role.is_confirm = true
    if role.save
      InfoMailer.with(user: user).user_confirmed.deliver_now
      redirect_to admin_users_path, notice: "#{user.email}を承認しました"
    else
      redirect_to admin_users_path, alert: "承認に失敗しました"
    end
  end

  def blogs
    @blogs = Blog.all
    @blogs = @blogs.where(is_publish: true) if params[:type] == 'is_publish'
    @blogs = @blogs.where(is_publish: false) if params[:type] == 'is_not_publish'
  end

  def blog_publish
    blog = Blog.find(params[:id])
    notice_txt = ''
    case params[:type]
    when 'be_publish'
      blog.is_publish = true
      blog.published_on = Time.zone.now
      notice_txt = '公開中'
    when 'be_not_publish'
      blog.is_publish = false
      blog.published_on = nil
      notice_txt = '非公開'
    end
    if blog.save
      Topic.create(title: "#{blog.title}を公開しました。")
      redirect_to admin_blogs_path, notice: "#{blog.title}を#{notice_txt}にしました"
    else
      redirect_to admin_blogs_path, notice: "#{blog.title}を#{notice_txt}にできませんでした"
    end
  end
end

app/views/admin/home/blogs.html.erb
<div class="container mt-5">
  <h1 class="profile-heading mb-5"><span>ブログ一覧</span></h1>
  <div class="mb-5">
    <%= link_to '全ブログ表示', admin_blogs_path, class: 'btn btn-success' %>
    <%= link_to '公開中ブログのみ表示', admin_blogs_path(type: 'is_publish'), class: 'btn btn-warning' %>
    <%= link_to '未公開ブログのみ表示', admin_blogs_path(type: 'is_not_publish'), class: 'btn btn-danger' %>
  </div>
  <table class="table text-center">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>タイトル</th>
        <th>内容</th>
        <th>ステータス</th>
        <th>公開日</th>
      </tr>
    </thead>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.id %></td>
        <td>
          <%= blog.title %>
          <%= link_to '削除する', blog_path(blog), class: 'btn btn-danger', method: :delete %>
        </td>
        <td><span class="badge badge-light"><%= blog.content.truncate(20) %></span></td>
        <td><span class="badge badge-secondary"><%= blog.is_publish? ? '公開中' : '未公開' %></span></td>
        <td>
          <% if !blog.is_publish? %>
            <%= link_to '公開する', admin_blog_publish_path(blog.id, type: 'be_publish'), method: :patch, class: 'btn btn-dark' %>
          <% else %>
            <%= link_to '非公開する', admin_blog_publish_path(blog.id, type: 'be_not_publish'), method: :patch, class: 'btn btn-dark' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= link_to 'ユーザー一覧', admin_users_path, class: 'btn btn-dark btn-lg' %>
</div>

app/views/admin/home/top.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">管理画面</h1>
    <p>ユーザーの承認や記事の公開・非公開を操作する</p>
    <%= link_to 'TOP', root_path, class: 'btn btn-dark btn-lg' %>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h2>ユーザー管理</h2>
      <p>ユーザーの承認や削除などを行う</p>
      <p>
        <%= link_to '一覧ページ', admin_users_path, class: 'btn btn-secondary' %>
      </p>
    </div>
    <div class="col-md-4">
      <h2>ブログ管理</h2>
      <p>ブログの公開・非公開や削除などを行う</p>
      <p>
        <%= link_to '一覧ページ', admin_blogs_path, class: 'btn btn-secondary' %>
      </p>
    </div>
  </div>
</div>

app/views/admin/home/user_logs.html.erb
<div class="container mt-5">
  <h1 class="profile-heading mb-5"><span><%= User.find(params[:id]).email %>視聴ログ一覧</span></h1>
  <table class="table text-center">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>視聴したページ</th>
        <th>視聴した時刻</th>
      </tr>
    </thead>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.id %></td>
        <td><%= link_to log.landing_on, log.landing_on %></td>
        <td><%= log.landing_at.try(:strftime, '%y年%m月%d日 %H:%M') %></td>
      </tr>
    <% end %>
  </table>
  <%= link_to 'ブログ一覧', admin_blogs_path, class: 'btn btn-dark btn-lg' %>
</div>

app/views/admin/home/users.html.erb
<div class="container mt-5">
  <h1 class="profile-heading mb-5"><span>ユーザー一覧</span></h1>
  <div class="mb-5">
    <%= link_to '全ユーザー表示', admin_users_path, class: 'btn btn-success' %>
    <%= link_to '承認済みユーザーのみ表示', admin_users_path(type: 'is_confirm'), class: 'btn btn-warning' %>
    <%= link_to '未承認ユーザーのみ表示', admin_users_path(type: 'is_not_confirm'), class: 'btn btn-danger' %>
  </div>
  <table class="table text-center">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>メールアドレス</th>
        <th>権限</th>
        <th>承認状況</th>
        <th>最終ログイン</th>
        <th>確認状況</th>
        <th>操作</th>
      </tr>
    </thead>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td>
          <%= link_to_if user.track_viewers.any?, user.email, admin_user_logs_path(id: user.id) %>
          <%= link_to '削除する', user_registration_path(id: user.id), class: 'btn btn-danger', method: :delete %>
        </td>
        <td><span class="badge badge-light"><%= user.role.auth %></span></td>
        <td><span class="badge badge-secondary"><%= user.role.is_confirm? ? '承認済' : '未承認' %></span></td>
        <td><span class="badge badge-secondary"><%= user.try(:current_sign_in_at).try(:strftime, '%y年%m月%d日 %H:%M') %></span></td>
        <td>
          <% if user.confirmed_at.nil? %>
            <span class="badge badge-warning">未確認</span>
          <% else %>
            <%= user.confirmed_at.strftime('%y年%m月%d日 %H:%M') %>
          <% end %>
        </td>
        <td>
          <% if !user.role.is_confirm? %>
            <%= link_to '承認する', admin_user_accept_path(user.id), method: :patch, class: 'btn btn-dark' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= link_to 'ブログ一覧', admin_blogs_path, class: 'btn btn-dark btn-lg' %>
</div>