config/routes.rb
Rails.application.routes.draw do
  namespace :apis do
    resources :favorites, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :blogs do
    post "/comment" => "comments#create", as: "comment"
    delete "/comment/:comment_id" => "comments#destroy", as: "comments"
    collection do
      get "/favorites" => "blogs#favorites", as: "favorites"
    end
  end
  post "/topic" => "topics#create", as: "topic"
  delete "/topic/:id" => "topics#destroy", as: "topics"
  resources :experiences
  root 'page#top'

  namespace :admin do
    root "home#top"
    get "users" => "home#users"
    get "user_logs/:id/" => "home#user_logs", as: 'user_logs'
    patch "/:id/user_accept" => "home#user_accept", as: 'user_accept'
    get "blogs" => "home#blogs"
    patch "/:id/blog_publish" => "home#blog_publish", as: 'blog_publish'
  end
  # LetterOpener
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Hirrot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <% if controller_name == 'blogs' && action_name == 'show' %>
      <%= show_meta_tags(title: @blog.title, description: @blog.content.truncate(20)) %>
    <% else %>
      <%= show_meta_tags %>
    <% end %>

    <link href="https://fonts.googleapis.com/css?family=Bai+Jamjuree" rel="stylesheet">
    <link href="https://fonts.googleapis.com/earlyaccess/roundedmplus1c.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header id="header">
      <nav id="global-nav">
        <div class="navToggle">
          <div class="icon"></div>
        </div>

        <ul class="clearfix">
          <li><%= link_to 'TOP', root_path %></li>
          <li><%= link_to 'EXPERIENCES', experiences_path %></li>
          <li><%= link_to 'BLOG', blogs_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to 'FAVORITES', favorites_blogs_path %></li>
            <li><%= link_to 'LOG OUT', destroy_user_session_path, method: :delete %></li>
            <li><%= link_to 'ADMIN', admin_root_path if current_user.admin? %></li>
          <% else %>
            <li class="auth-menu">
              <%= link_to 'SIGN UP', new_user_registration_path, class: 'auth-menu-item' %>
              or
              <%= link_to 'LOG IN', new_user_session_path, class: 'auth-menu-item' %>
            </li>
          <% end %>
        </ul>
      </nav>
    </header>
    <main style="margin-bottom:60px;">
      <% if notice %><div class="alert alert-success text-center mb-0"><%= notice %></div><% end %>
      <% if alert %><div class="alert alert-warning text-center mb-0"><%= alert %></div><% end %>
      <%= yield %>
    </main>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  </body>
</html>